name: Python_Checker

on: 
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: install
        run: |
          pip install -U pytest
      - run: python3 -m unittest testy.py
